use_frameworks!

platform :ios, '9.0'

target 'SDK-ArticleManager_Example' do
  pod 'SDK-ArticleManager', :path => '../'

  target 'SDK-ArticleManager_Tests' do
    inherit! :search_paths

    
  end
end
